### ISSUE TITLE
update version ?

### ISSUE THREAD

**Issue by 6lv1-blr** [mfreiholz/iF.SVNAdmin#167]
when opening https://svn.opales.vision/svnadmin/repositorylist.php

if I click on one repository, I get this page :

Error: Call to undefined function xml_parser_create()

#0 /var/www/html/svnadmin/classes/providers/RepositoryViewProvider.class.php(220): IF_SVNClientC->svn_list()
#1 /var/www/html/svnadmin/repositoryview.php(55): svnadmin\providers\RepositoryViewProvider->listPath()
#2 {main}

with ubuntu 20.04, apache 2.4.41, PHP 7.4.3, svnadmin 1.13.0, iF.SVNAdmin 1.6.2
using a docker solution from me : 
https://github.com/6lv1-blr/docker-ubuntu-svn-ssl-iF.SvnAdmin

same with ubuntu 20.10:groovy, apache 2.4.46, PHP 7.4.9, svnadmin 1.14.0, iF.SVNAdmin 1.6.2

it works with ubuntu 14.04, apache 2.4.7, PHP 5.5.9-1ubuntu4.29, svnadmin 1.8.8, iF.SVNAdmin 1.6.2
from this instructions : https://kb.synology.com/en-my/DSM/tutorial/How_to_launch_an_SVN_server_based_on_Docker_on_your_Synology_NAS
but svn version is way too old...

**Comment by 6lv1-blr** [comment]
solve by myself
xml is not include in php 7
on ubuntu-like
apt install php-xml
